<?php

declare(strict_types=1);

namespace Coffesoft\LaravelBeacon\Intelligence;

use Coffesoft\LaravelBeacon\Cache\ScanCache;

/**
 * v4.0 Diff Engine
 *
 * Compares current project state against previous scan cache.
 * Outputs: added files, removed files, modified files, changed models,
 * changed controllers, changed services, changed routes, changed migrations,
 * and an impact analysis.
 */
class DiffEngine
{
    public function __construct(
        private readonly ScanCache $scanCache,
    ) {}

    /**
     * @param array<string, mixed> $data Current scanned data
     * @return array<string, mixed>
     */
    public function analyze(array $data): array
    {
        $currentFiles = $this->getCurrentProjectFiles();
        $cachedPaths = $this->scanCache->getCachedPaths();

        // Detect file changes
        [$changed, $unchanged] = $this->scanCache->detectChanges($currentFiles);

        // Detect removed files
        $currentRelative = array_map(fn($f) => $this->relativePath($f), $currentFiles);
        $removed = array_diff($cachedPaths, $currentRelative);

        // Detect added files
        $added = array_diff($currentRelative, $cachedPaths);

        // Detect modified files (changed but not added)
        $modified = [];
        foreach ($changed as $f) {
            $rel = $this->relativePath($f);
            if (!in_array($rel, $added)) {
                $modified[] = $rel;
            }
        }

        // Categorize changes
        $changedModels = $this->filterByType($modified, 'Models');
        $changedControllers = $this->filterByType($modified, 'Http/Controllers');
        $changedServices = $this->filterByType($modified, 'Services');
        $changedMigrations = $this->filterByType($modified, 'migrations');

        // Impact analysis
        $impact = $this->analyzeImpact($data, $changedModels, $changedControllers, $changedServices);

        $lines = [];

        $lines[] = '# Beacon Diff Report';
        $lines[] = '';
        $lines[] = '> Generated by Laravel Beacon v4.0 — AI Working Context';
        $lines[] = '> Compares current project against last scan.';
        $lines[] = '';
        $lines[] = '---';
        $lines[] = '';

        $lines[] = '## Summary';
        $lines[] = '';
        $lines[] = "| Metric | Count |";
        $lines[] = "|--------|-------|";
        $lines[] = "| **Added Files** | " . count($added) . " |";
        $lines[] = "| **Removed Files** | " . count($removed) . " |";
        $lines[] = "| **Modified Files** | " . count($modified) . " |";
        $lines[] = "| **Changed Models** | " . count($changedModels) . " |";
        $lines[] = "| **Changed Controllers** | " . count($changedControllers) . " |";
        $lines[] = "| **Changed Services** | " . count($changedServices) . " |";
        $lines[] = "| **Changed Migrations** | " . count($changedMigrations) . " |";
        $lines[] = '';
        $lines[] = '---';
        $lines[] = '';

        if (!empty($added)) {
            $lines[] = '## Added Files';
            $lines[] = '';
            foreach ($added as $f) {
                $lines[] = "- `{$f}`";
            }
            $lines[] = '';
        }

        if (!empty($removed)) {
            $lines[] = '## Removed Files';
            $lines[] = '';
            foreach ($removed as $f) {
                $lines[] = "- `{$f}`";
            }
            $lines[] = '';
        }

        if (!empty($modified)) {
            $lines[] = '## Modified Files';
            $lines[] = '';
            foreach ($modified as $f) {
                $lines[] = "- `{$f}`";
            }
            $lines[] = '';
        }

        if (!empty($changedModels)) {
            $lines[] = '## Changed Models';
            $lines[] = '';
            foreach ($changedModels as $m) {
                $lines[] = "- `{$m}`";
            }
            $lines[] = '';
        }

        if (!empty($changedControllers)) {
            $lines[] = '## Changed Controllers';
            $lines[] = '';
            foreach ($changedControllers as $c) {
                $lines[] = "- `{$c}`";
            }
            $lines[] = '';
        }

        if (!empty($changedServices)) {
            $lines[] = '## Changed Services';
            $lines[] = '';
            foreach ($changedServices as $s) {
                $lines[] = "- `{$s}`";
            }
            $lines[] = '';
        }

        if (!empty($changedMigrations)) {
            $lines[] = '## Changed Migrations';
            $lines[] = '';
            foreach ($changedMigrations as $m) {
                $lines[] = "- `{$m}`";
            }
            $lines[] = '';
        }

        if (!empty($impact)) {
            $lines[] = '---';
            $lines[] = '## Impact Analysis';
            $lines[] = '';
            foreach ($impact as $i) {
                $lines[] = "- **{$i['type']}**: {$i['message']}";
                if (!empty($i['affected'])) {
                    $lines[] = "  - Affected: " . implode(', ', $i['affected']);
                }
            }
            $lines[] = '';
        }

        return [
            'diff' => [
                'added' => array_values($added),
                'removed' => array_values($removed),
                'modified' => $modified,
                'changed_models' => $changedModels,
                'changed_controllers' => $changedControllers,
                'changed_services' => $changedServices,
                'changed_migrations' => $changedMigrations,
                'impact' => $impact,
                'markdown_content' => implode("\n", $lines),
                'confidence' => 90,
            ],
        ];
    }

    private function getCurrentProjectFiles(): array
    {
        $files = [];
        $dirs = [
            app_path('Models'),
            app_path('Http/Controllers'),
            app_path('Services'),
            app_path('Repositories'),
            app_path('Http/Requests'),
            app_path('Policies'),
            app_path('Events'),
            app_path('Listeners'),
            app_path('Jobs'),
            app_path('Notifications'),
            app_path('Mail'),
            app_path('Console/Commands'),
            database_path('migrations'),
        ];

        foreach ($dirs as $dir) {
            if (!is_dir($dir)) continue;
            $iterator = new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($dir));
            foreach ($iterator as $file) {
                if ($file->isFile() && $file->getExtension() === 'php') {
                    $files[] = $file->getPathname();
                }
            }
        }

        return $files;
    }

    private function relativePath(string $path): string
    {
        $base = base_path();
        if (str_starts_with($path, $base)) {
            return substr($path, strlen($base) + 1);
        }
        return $path;
    }

    private function filterByType(array $files, string $type): array
    {
        return array_values(array_filter($files, fn($f) => str_contains($f, "/{$type}/")));
    }

    private function analyzeImpact(array $data, array $changedModels, array $changedControllers, array $changedServices): array
    {
        $impact = [];

        // Analyze model change impact
        foreach ($changedModels as $modelPath) {
            $modelName = pathinfo($modelPath, PATHINFO_FILENAME);
            $affected = [];

            foreach ($data['controllers']['items'] ?? [] as $c) {
                if (str_contains($c['name'], $modelName)) {
                    $affected[] = "controller:{$c['name']}";
                }
            }
            foreach ($data['services']['items'] ?? [] as $s) {
                if (str_contains($s['name'], $modelName)) {
                    $affected[] = "service:{$s['name']}";
                }
                foreach ($s['referenced_models'] ?? [] as $ref) {
                    if (str_contains($ref, "\\{$modelName}")) {
                        $affected[] = "service:{$s['name']}";
                        break;
                    }
                }
            }
            foreach ($data['repositories']['items'] ?? [] as $r) {
                foreach ($r['referenced_models'] ?? [] as $ref) {
                    if (str_contains($ref, "\\{$modelName}")) {
                        $affected[] = "repository:{$r['name']}";
                        break;
                    }
                }
            }

            $impact[] = [
                'type' => 'model_changed',
                'message' => "{$modelName} model was modified",
                'affected' => array_values(array_unique($affected)),
                'confidence' => 85,
            ];
        }

        // Analyze controller change impact
        foreach ($changedControllers as $ctrlPath) {
            $ctrlName = pathinfo($ctrlPath, PATHINFO_FILENAME);
            $affected = [];

            foreach ($data['routes']['items'] ?? [] as $r) {
                if (str_contains($r['action'] ?? '', "\\{$ctrlName}@") || str_contains($r['action'] ?? '', "{$ctrlName}@")) {
                    $affected[] = "route:{$r['uri']}";
                }
            }

            foreach ($data['views']['items'] ?? [] as $v) {
                // Views that might be returned by this controller
                $modelName = preg_replace('/Controller$/', '', $ctrlName);
                $viewPattern = strtolower(preg_replace('/([a-z])([A-Z])/', '$1.$2', $modelName));
                if ($viewPattern && str_contains($v['name'] ?? '', $viewPattern)) {
                    $affected[] = "view:{$v['name']}";
                }
            }

            $impact[] = [
                'type' => 'controller_changed',
                'message' => "{$ctrlName} was modified",
                'affected' => array_values(array_unique($affected)),
                'confidence' => 80,
            ];
        }

        return $impact;
    }
}