<?php

declare(strict_types=1);

namespace Coffesoft\LaravelBeacon\Intelligence;

/**
 * v4.0 Task Context Engine
 *
 * Given a task description (e.g. "Create attendance system"),
 * analyzes all scanned Beacon knowledge and determines:
 *
 * - Related models, controllers, services, repositories
 * - Files that probably need modification
 * - New files that should be created
 * - Dependencies, risks, similar implementations
 *
 * Uses pattern matching on class names, routes, and database tables
 * to find the most relevant parts of the project.
 */
class TaskContextEngine
{
    /**
     * @param array<string, mixed> $data Full scanned context
     * @param string $task The task description
     * @return array<string, mixed>
     */
    public function analyze(array $data, string $task): array
    {
        // Extract keywords from the task
        $keywords = $this->extractKeywords($task);
        $mainEntity = $this->extractMainEntity($task);

        // Score all project entities against the task
        $scoredModels = $this->scoreModels($data, $keywords, $mainEntity);
        $scoredControllers = $this->scoreControllers($data, $keywords, $mainEntity);
        $scoredServices = $this->scoreServices($data, $keywords, $mainEntity);
        $scoredRoutes = $this->scoreRoutes($data, $keywords, $mainEntity);
        $scoredTables = $this->scoreTables($data, $keywords, $mainEntity);
        $scoredViews = $this->scoreViews($data, $keywords, $mainEntity);

        // Determine existing similar implementations
        $similarImplementations = $this->findSimilarImplementations($data, $mainEntity);

        // Determine new files needed
        $newFilesNeeded = $this->determineNewFiles($data, $mainEntity, $keywords);

        // Determine files needing modification
        $filesToModify = $this->determineFilesToModify($data, $scoredModels, $scoredControllers, $scoredServices);

        // Risks assessment
        $risks = $this->assessRisks($data, $mainEntity);

        // Dependencies
        $dependencies = $this->determineDependencies($data, $mainEntity);

        $lines = [];

        $lines[] = "# Task Context: {$task}";
        $lines[] = '';
        $lines[] = '> Generated by Laravel Beacon v4.0 — AI Working Context';
        $lines[] = '> This file prepares the exact context an AI needs before coding this task.';
        $lines[] = '> Confidence scores (0–100) indicate relevance to your task.';
        $lines[] = '';
        $lines[] = '---';
        $lines[] = '';

        // Task summary
        $lines[] = '## Task Summary';
        $lines[] = '';
        $lines[] = "- **Task:** {$task}";
        $lines[] = "- **Main Entity Detected:** " . ($mainEntity ?: 'Not determined');
        $lines[] = "- **Keywords:** " . implode(', ', $keywords);
        $lines[] = '';
        $lines[] = '---';
        $lines[] = '';

        // Related models
        $highModels = array_filter($scoredModels, fn($m) => $m['score'] >= 50);
        if (!empty($highModels)) {
            $lines[] = '## Related Models';
            $lines[] = '';
            $lines[] = '| Model | Relevance | Reason |';
            $lines[] = '|-------|-----------|--------|';
            usort($highModels, fn($a, $b) => $b['score'] <=> $a['score']);
            foreach ($highModels as $m) {
                $lines[] = "| `{$m['name']}` | {$m['score']}% | {$m['reason']} |";
            }
            $lines[] = '';
        }

        // Related controllers
        $highControllers = array_filter($scoredControllers, fn($c) => $c['score'] >= 40);
        if (!empty($highControllers)) {
            $lines[] = '## Related Controllers';
            $lines[] = '';
            $lines[] = '| Controller | Relevance | Reason |';
            $lines[] = '|-----------|-----------|--------|';
            usort($highControllers, fn($a, $b) => $b['score'] <=> $a['score']);
            foreach ($highControllers as $c) {
                $lines[] = "| `{$c['name']}` | {$c['score']}% | {$c['reason']} |";
            }
            $lines[] = '';
        }

        // Related services
        $highServices = array_filter($scoredServices, fn($s) => $s['score'] >= 40);
        if (!empty($highServices)) {
            $lines[] = '## Related Services';
            $lines[] = '';
            $lines[] = '| Service | Relevance | Reason |';
            $lines[] = '|---------|-----------|--------|';
            usort($highServices, fn($a, $b) => $b['score'] <=> $a['score']);
            foreach ($highServices as $s) {
                $lines[] = "| `{$s['name']}` | {$s['score']}% | {$s['reason']} |";
            }
            $lines[] = '';
        }

        // Related routes
        $highRoutes = array_filter($scoredRoutes, fn($r) => $r['score'] >= 40);
        if (!empty($highRoutes)) {
            $lines[] = '## Related Routes';
            $lines[] = '';
            $lines[] = '| Route | Methods | Relevance |';
            $lines[] = '|-------|---------|-----------|';
            usort($highRoutes, fn($a, $b) => $b['score'] <=> $a['score']);
            foreach (array_slice($highRoutes, 0, 10) as $r) {
                $methods = implode(',', array_diff($r['methods'] ?? [], ['HEAD']));
                $lines[] = "| `{$r['uri']}` | {$methods} | {$r['score']}% |";
            }
            $lines[] = '';
        }

        // Related database tables
        $highTables = array_filter($scoredTables, fn($t) => $t['score'] >= 40);
        if (!empty($highTables)) {
            $lines[] = '## Related Database Tables';
            $lines[] = '';
            $lines[] = '| Table | Relevance |';
            $lines[] = '|------|-----------|';
            usort($highTables, fn($a, $b) => $b['score'] <=> $a['score']);
            foreach ($highTables as $t) {
                $lines[] = "| `{$t['name']}` | {$t['score']}% |";
            }
            $lines[] = '';
        }

        // Files to modify
        if (!empty($filesToModify)) {
            $lines[] = '---';
            $lines[] = '## Files That Probably Need Modification';
            $lines[] = '';
            $lines[] = '| File | Type | Action |';
            $lines[] = '|------|------|--------|';
            foreach ($filesToModify as $f) {
                $lines[] = "| `{$f['path']}` | {$f['type']} | {$f['action']} |";
            }
            $lines[] = '';
        }

        // New files needed
        if (!empty($newFilesNeeded)) {
            $lines[] = '---';
            $lines[] = '## New Files That Should Be Created';
            $lines[] = '';
            $lines[] = '| Suggested Path | Type | Reason |';
            $lines[] = '|---------------|------|--------|';
            foreach ($newFilesNeeded as $f) {
                $lines[] = "| `{$f['path']}` | {$f['type']} | {$f['reason']} |";
            }
            $lines[] = '';
        }

        // Similar implementations
        if (!empty($similarImplementations)) {
            $lines[] = '---';
            $lines[] = '## Similar Implementations (Reference)';
            $lines[] = '';
            foreach ($similarImplementations as $impl) {
                $lines[] = "- **{$impl['name']}** ({$impl['type']}): {$impl['description']}";
            }
            $lines[] = '';
        }

        // Dependencies
        if (!empty($dependencies)) {
            $lines[] = '---';
            $lines[] = '## Dependencies';
            $lines[] = '';
            foreach ($dependencies as $dep) {
                $lines[] = "- {$dep}";
            }
            $lines[] = '';
        }

        // Risks
        if (!empty($risks)) {
            $lines[] = '---';
            $lines[] = '## Possible Risks';
            $lines[] = '';
            foreach ($risks as $risk) {
                $lines[] = "- **{$risk['type']}**: {$risk['message']}";
            }
            $lines[] = '';
        }

        return [
            'task_context' => [
                'task' => $task,
                'main_entity' => $mainEntity,
                'keywords' => $keywords,
                'markdown_content' => implode("\n", $lines),
                'json' => [
                    'related_models' => array_values($highModels),
                    'related_controllers' => array_values($highControllers),
                    'related_services' => array_values($highServices),
                    'related_routes' => array_values($highRoutes),
                    'related_tables' => array_values($highTables),
                    'files_to_modify' => $filesToModify,
                    'new_files_needed' => $newFilesNeeded,
                    'similar_implementations' => $similarImplementations,
                    'dependencies' => $dependencies,
                    'risks' => $risks,
                ],
                'confidence' => 75,
            ],
        ];
    }

    private function extractKeywords(string $task): array
    {
        // Remove common words and split
        $stopWords = ['a', 'an', 'the', 'and', 'or', 'but', 'in', 'on', 'at', 'to', 'for',
                       'of', 'with', 'by', 'from', 'as', 'is', 'was', 'are', 'be', 'been',
                       'create', 'make', 'add', 'new', 'system', 'module', 'feature', 'build',
                       'implement', 'develop', 'integrate', 'set', 'up', 'out', 'get', 'all'];

        $words = preg_split('/[\s,]+/', strtolower($task));
        $keywords = [];
        foreach ($words as $word) {
            $word = trim($word, '.,;:!?\'"');
            if (strlen($word) > 2 && !in_array($word, $stopWords)) {
                $keywords[] = $word;
            }
        }

        return array_values(array_unique($keywords));
    }

    private function extractMainEntity(string $task): ?string
    {
        // Try to extract the main noun/entity from the task
        $patterns = [
            '/create\s+(?:a|an)\s+(\w+)/i',
            '/create\s+(\w+)\s+system/i',
            '/add\s+(?:a|an)\s+(\w+)/i',
            '/add\s+(\w+)\s+(?:system|module|feature)/i',
            '/build\s+(?:a|an)\s+(\w+)/i',
            '/manage\s+(\w+)/i',
            '/(\w+)\s+management/i',
            '/(\w+)\s+system/i',
        ];

        foreach ($patterns as $pattern) {
            if (preg_match($pattern, $task, $matches)) {
                $entity = $matches[1];
                // Convert to PascalCase
                return ucfirst(strtolower($entity));
            }
        }

        // Fallback: use first significant keyword
        $keywords = $this->extractKeywords($task);
        return !empty($keywords) ? ucfirst($keywords[0]) : null;
    }

    private function scoreModels(array $data, array $keywords, ?string $mainEntity): array
    {
        $scored = [];
        foreach ($data['models']['items'] ?? [] as $m) {
            $score = 0;
            $reasons = [];

            $name = strtolower($m['name']);

            // Direct match with main entity
            if ($mainEntity && strtolower($mainEntity) === $name) {
                $score += 90;
                $reasons[] = 'Direct match with task entity';
            }

            // Partial match with main entity
            if ($mainEntity && str_contains($name, strtolower($mainEntity))) {
                $score += 60;
                $reasons[] = 'Contains task entity name';
            }

            // Keyword matches in fillable attributes
            $fillables = array_map('strtolower', $m['fillable'] ?? []);
            foreach ($keywords as $kw) {
                if (in_array($kw, $fillables)) {
                    $score += 15;
                    $reasons[] = "Has '{$kw}' attribute";
                    break;
                }
            }

            // Keyword matches in relations
            foreach ($m['relations'] ?? [] as $type => $count) {
                foreach ($keywords as $kw) {
                    if (str_contains($type, $kw)) {
                        $score += 10;
                        break;
                    }
                }
            }

            // Keyword matches in name
            foreach ($keywords as $kw) {
                if (str_contains($name, $kw)) {
                    $score += 20;
                    $reasons[] = "Keyword '{$kw}' found in name";
                    break;
                }
            }

            if ($score > 0) {
                $scored[] = [
                    'name' => $m['name'],
                    'type' => 'model',
                    'score' => min($score, 95),
                    'reason' => implode('; ', array_slice($reasons, 0, 2)),
                    'fillable' => $m['fillable'] ?? [],
                    'relations' => $m['relations'] ?? [],
                ];
            }
        }

        return $scored;
    }

    private function scoreControllers(array $data, array $keywords, ?string $mainEntity): array
    {
        $scored = [];

        foreach ($data['controllers']['items'] ?? [] as $c) {
            $score = 0;
            $reasons = [];
            $name = strtolower($c['name']);

            // Direct match with main entity
            if ($mainEntity) {
                $ctrlEntity = strtolower($mainEntity . 'controller');
                if ($name === $ctrlEntity) {
                    $score += 90;
                    $reasons[] = 'Direct controller for task entity';
                } elseif (str_contains($name, strtolower($mainEntity))) {
                    $score += 50;
                    $reasons[] = 'Related to task entity';
                }
            }

            // Keyword matches
            foreach ($keywords as $kw) {
                if (str_contains($name, $kw)) {
                    $score += 20;
                    $reasons[] = "Keyword '{$kw}' in name";
                    break;
                }
            }

            // Methods that suggest relevance
            foreach ($c['methods'] ?? [] as $method) {
                foreach ($keywords as $kw) {
                    if (str_contains(strtolower($method), $kw)) {
                        $score += 5;
                        break;
                    }
                }
            }

            if ($score > 0) {
                $scored[] = [
                    'name' => $c['name'],
                    'type' => 'controller',
                    'score' => min($score, 95),
                    'reason' => implode('; ', array_slice($reasons, 0, 2)),
                    'methods' => $c['methods'] ?? [],
                    'path' => $c['path'] ?? '',
                ];
            }
        }

        return $scored;
    }

    private function scoreServices(array $data, array $keywords, ?string $mainEntity): array
    {
        $scored = [];

        foreach ($data['services']['items'] ?? [] as $s) {
            $score = 0;
            $reasons = [];
            $name = strtolower($s['name']);

            if ($mainEntity) {
                $svcEntity = strtolower($mainEntity . 'service');
                if ($name === $svcEntity) {
                    $score += 90;
                    $reasons[] = 'Direct service for task entity';
                } elseif (str_contains($name, strtolower($mainEntity))) {
                    $score += 50;
                    $reasons[] = 'Related to task entity';
                }
            }

            foreach ($keywords as $kw) {
                if (str_contains($name, $kw)) {
                    $score += 20;
                    $reasons[] = "Keyword '{$kw}' in name";
                    break;
                }
            }

            if ($score > 0) {
                $scored[] = [
                    'name' => $s['name'],
                    'type' => 'service',
                    'score' => min($score, 95),
                    'reason' => implode('; ', array_slice($reasons, 0, 2)),
                    'methods' => $s['methods'] ?? [],
                ];
            }
        }

        return $scored;
    }

    private function scoreRoutes(array $data, array $keywords, ?string $mainEntity): array
    {
        $scored = [];

        foreach ($data['routes']['items'] ?? [] as $r) {
            $score = 0;
            $uri = strtolower($r['uri'] ?? '');

            if ($mainEntity) {
                $entityRoute = strtolower($mainEntity);
                if (str_contains($uri, $entityRoute)) {
                    $score += 60;
                }
            }

            foreach ($keywords as $kw) {
                if (str_contains($uri, $kw)) {
                    $score += 25;
                    break;
                }
            }

            if ($score > 0) {
                $scored[] = [
                    'uri' => $r['uri'] ?? '',
                    'methods' => $r['methods'] ?? [],
                    'score' => min($score, 95),
                ];
            }
        }

        return $scored;
    }

    private function scoreTables(array $data, array $keywords, ?string $mainEntity): array
    {
        $scored = [];

        foreach ($data['database']['tables'] ?? [] as $t) {
            $score = 0;
            $name = strtolower($t['name']);

            if ($mainEntity) {
                $tableEntity = strtolower($this->entityToTable($mainEntity));
                if ($name === $tableEntity) {
                    $score += 90;
                } elseif (str_contains($name, strtolower($mainEntity))) {
                    $score += 50;
                }
            }

            foreach ($keywords as $kw) {
                if (str_contains($name, $kw)) {
                    $score += 20;
                    break;
                }
            }

            if ($score > 0) {
                $scored[] = [
                    'name' => $t['name'],
                    'score' => min($score, 95),
                    'columns' => $t['columns'] ?? [],
                ];
            }
        }

        return $scored;
    }

    private function scoreViews(array $data, array $keywords, ?string $mainEntity): array
    {
        $scored = [];

        foreach ($data['blade']['views'] ?? [] as $v) {
            $score = 0;
            $name = strtolower($v['name'] ?? '');

            if ($mainEntity) {
                $viewEntity = strtolower($mainEntity);
                if (str_contains($name, $viewEntity)) {
                    $score += 50;
                }
            }

            foreach ($keywords as $kw) {
                if (str_contains($name, $kw)) {
                    $score += 20;
                    break;
                }
            }

            if ($score > 0) {
                $scored[] = [
                    'name' => $v['name'] ?? '',
                    'score' => min($score, 90),
                    'path' => $v['path'] ?? '',
                ];
            }
        }

        return $scored;
    }

    private function findSimilarImplementations(array $data, ?string $mainEntity): array
    {
        $similar = [];
        if (!$mainEntity) return $similar;

        // Find CRUD controllers as pattern references
        foreach ($data['controllers']['items'] ?? [] as $c) {
            if (($c['is_crud'] ?? false) && strtolower($c['name']) !== strtolower($mainEntity . 'Controller')) {
                $similar[] = [
                    'name' => $c['name'],
                    'type' => 'controller',
                    'description' => 'CRUD controller — reference pattern for CRUD operations',
                ];
                break; // Just one example
            }
        }

        // Find services as pattern references
        foreach ($data['services']['items'] ?? [] as $s) {
            $methods = $s['methods'] ?? [];
            if (count($methods) >= 3) {
                $similar[] = [
                    'name' => $s['name'],
                    'type' => 'service',
                    'description' => 'Service with ' . count($methods) . ' methods — reference pattern for business logic',
                ];
                break;
            }
        }

        return $similar;
    }

    private function determineNewFiles(array $data, ?string $mainEntity, array $keywords): array
    {
        $newFiles = [];
        if (!$mainEntity) return $newFiles;

        $entity = $mainEntity;
        $plural = $this->entityToTable($entity);

        // Check if model exists
        $modelExists = false;
        foreach ($data['models']['items'] ?? [] as $m) {
            if ($m['name'] === $entity) {
                $modelExists = true;
                break;
            }
        }
        if (!$modelExists) {
            $newFiles[] = [
                'path' => "app/Models/{$entity}.php",
                'type' => 'model',
                'reason' => "{$entity} model does not exist yet",
            ];
        }

        // Check if controller exists
        $controllerExists = false;
        foreach ($data['controllers']['items'] ?? [] as $c) {
            if ($c['name'] === $entity . 'Controller') {
                $controllerExists = true;
                break;
            }
        }
        if (!$controllerExists) {
            $newFiles[] = [
                'path' => "app/Http/Controllers/{$entity}Controller.php",
                'type' => 'controller',
                'reason' => "{$entity} controller does not exist yet",
            ];
        }

        // Check if service exists
        $serviceExists = false;
        foreach ($data['services']['items'] ?? [] as $s) {
            if ($s['name'] === $entity . 'Service') {
                $serviceExists = true;
                break;
            }
        }
        if (!$serviceExists) {
            $newFiles[] = [
                'path' => "app/Services/{$entity}Service.php",
                'type' => 'service',
                'reason' => "{$entity} service does not exist yet",
            ];
        }

        // Check if migration exists
        $tableName = $this->entityToTable($entity);
        $migrationExists = false;
        foreach ($data['database']['tables'] ?? [] as $t) {
            if ($t['name'] === $tableName) {
                $migrationExists = true;
                break;
            }
        }
        if (!$migrationExists) {
            $newFiles[] = [
                'path' => "database/migrations/create_{$tableName}_table.php",
                'type' => 'migration',
                'reason' => "{$tableName} table does not exist yet",
            ];
        }

        // Check if requests exist
        $storeRequestExists = false;
        $updateRequestExists = false;
        foreach ($data['form_requests']['items'] ?? [] as $r) {
            if ($r['name'] === "Store{$entity}Request") $storeRequestExists = true;
            if ($r['name'] === "Update{$entity}Request") $updateRequestExists = true;
        }
        if (!$storeRequestExists) {
            $newFiles[] = [
                'path' => "app/Http/Requests/Store{$entity}Request.php",
                'type' => 'form_request',
                'reason' => "Store request for {$entity} does not exist",
            ];
        }
        if (!$updateRequestExists) {
            $newFiles[] = [
                'path' => "app/Http/Requests/Update{$entity}Request.php",
                'type' => 'form_request',
                'reason' => "Update request for {$entity} does not exist",
            ];
        }

        // Check if policy exists
        $policyExists = false;
        foreach ($data['policies']['items'] ?? [] as $p) {
            if ($p['name'] === $entity . 'Policy') {
                $policyExists = true;
                break;
            }
        }
        if (!$policyExists) {
            $newFiles[] = [
                'path' => "app/Policies/{$entity}Policy.php",
                'type' => 'policy',
                'reason' => "Policy for {$entity} does not exist yet",
            ];
        }

        return $newFiles;
    }

    private function determineFilesToModify(array $data, array $scoredModels, array $scoredControllers, array $scoredServices): array
    {
        $files = [];

        // High-scoring existing files that need modification
        foreach ($scoredControllers as $c) {
            if ($c['score'] >= 70 && !empty($c['path'])) {
                $files[] = [
                    'path' => "app/Http/Controllers/" . $c['path'],
                    'type' => 'controller',
                    'action' => 'Add new methods for the task',
                ];
            }
        }

        foreach ($scoredServices as $s) {
            if ($s['score'] >= 70) {
                $files[] = [
                    'path' => "app/Services/" . ($s['name'] ?? '') . ".php",
                    'type' => 'service',
                    'action' => 'Add business logic for the task',
                ];
            }
        }

        // Routes file
        $files[] = [
            'path' => 'routes/web.php',
            'type' => 'route',
            'action' => 'Add new routes for the task',
        ];

        return $files;
    }

    private function assessRisks(array $data, ?string $mainEntity): array
    {
        $risks = [];
        if (!$mainEntity) return $risks;

        // Find resources already using this entity name
        $conflicts = [];
        foreach ($data['models']['items'] ?? [] as $m) {
            if (str_contains(strtolower($m['name']), strtolower($mainEntity))) {
                $conflicts[] = "model:{$m['name']}";
            }
        }

        if (!empty($conflicts)) {
            $risks[] = [
                'type' => 'name_conflict',
                'message' => "The name '{$mainEntity}' partially matches existing: " . implode(', ', $conflicts) . '. Verify naming is correct.',
            ];
        }

        // Check if main entity table would conflict
        $tableName = $this->entityToTable($mainEntity);
        foreach ($data['database']['tables'] ?? [] as $t) {
            if (str_contains($t['name'], $tableName) && $t['name'] !== $tableName) {
                $risks[] = [
                    'type' => 'table_conflict',
                    'message' => "Table '{$t['name']}' partially matches '{$tableName}'. Ensure migration naming is correct.",
                ];
                break;
            }
        }

        return $risks;
    }

    private function determineDependencies(array $data, ?string $mainEntity): array
    {
        $deps = [];

        // Base Laravel dependencies
        $deps[] = 'Laravel framework (already installed)';

        // Check if spatie/laravel-permission is needed for policies
        if (!empty($data['policies']['items'])) {
            $deps[] = 'Policies already set up — follow existing authorization pattern';
        }

        // Reference existing packages
        foreach ($data['packages']['items'] ?? [] as $p) {
            if (in_array($p['category'], ['admin_panel', 'media', 'payments', 'search'])) {
                $deps[] = "Existing package: {$p['name']} ({$p['purpose']})";
                break;
            }
        }

        return $deps;
    }

    private function entityToTable(string $entity): string
    {
        return strtolower(preg_replace('/([a-z])([A-Z])/', '$1_$2', $entity)) . 's';
    }
}